### ISSUE TITLE
AttributeError: 'code' object has no attribute 'co_exceptiontable'

### ISSUE THREAD

**Issue by ghost** [0x3C50/pyobf2#1]
[16:03:03] The output path at output.py already exists, choosing alternative...                                                                                                                           main.py:138
           Found one: output_0.py                                                                                                                                                                         main.py:152
           Parsing AST...                                                                                                                                                                                 main.py:155
           Executed transformer fstrToFormatSeq                                                                                                                                                           main.py:116
           Executed transformer intObfuscator                                                                                                                                                             main.py:116
           Executed transformer encodeStrings                                                                                                                                                             main.py:116
           Executed transformer renamer                                                                                                                                                                   main.py:116
           Executed transformer replaceAttribSet                                                                                                                                                          main.py:116
           Executed transformer collector                                                                                                                                                                 main.py:116
Obfuscating... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━  86% -:--:--
```Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xor7/pyobf2/obfuscator/__main__.py", line 23, in <module>
    launch()
  File "/home/xor7/pyobf2/obfuscator/__main__.py", line 9, in launch
    main.main()
  File "/home/xor7/pyobf2/obfuscator/main.py", line 104, in main
    go()
  File "/home/xor7/pyobf2/obfuscator/main.py", line 157, in go
    compiled_ast = transform_source(compiled_ast)
  File "/home/xor7/pyobf2/obfuscator/main.py", line 115, in transform_source
    c_ast = t.transform(c_ast)
  File "/home/xor7/pyobf2/obfuscator/transformers.py", line 675, in transform
    return self.do_enc_pass(ast_mod)
  File "/home/xor7/pyobf2/obfuscator/transformers.py", line 651, in do_enc_pass
    main_loader = self.create_code_obj_loader(tn, compiled_code_obj)
  File "/home/xor7/pyobf2/obfuscator/transformers.py", line 389, in create_code_obj_loader
    collected_args = self.args_from_co(compiled_code_obj)
  File "/home/xor7/pyobf2/obfuscator/transformers.py", line 341, in args_from_co
    return [getattr(code, x) if not isinstance(x, tuple) else x[1] for x in self._ctype_arg_names]
  File "/home/xor7/pyobf2/obfuscator/transformers.py", line 341, in <listcomp>
    return [getattr(code, x) if not isinstance(x, tuple) else x[1] for x in self._ctype_arg_names]
AttributeError: 'code' object has no attribute 'co_exceptiontable'```

**Comment by 0x3C50** [comment]
which py ver

**Comment by 0x3C50** [comment]
![grafik](https://user-images.githubusercontent.com/99053360/210086782-877783b4-9e47-4e6f-a2b9-363ba1c5c39f.png)
![grafik](https://user-images.githubusercontent.com/99053360/210086818-dda6f14e-3db2-41c4-8afb-9dcbdf814136.png)
simply an issue of skill

**Comment by ghost** [comment]
☠️
